### ISSUE TITLE
Implement all methods that exist in node-swc

### ISSUE THREAD

**Issue by littledivy** [nestdotland/deno_swc#12]
Implemented in `node-swc`
- [x] `parse` - #10  
- [ ] `parseSync` 
- [ ] `parseFile` 
- [ ] `parseFileSync`
- [x] `transform` - #18 
- [ ] `transformSync`
- [ ] `transformFile`  
- [ ] `transformFileSync`  
- [x] `print` - #15   
- [x] `bundle` - #14 

Extras (not implmented in `node-swc`)
- [x] `analyzer`

**Comment by divy-work** [comment]
@wongjiahau Do you think we should have `async` alternatives for all the ops (like https://github.com/swc-project/swc/blob/master/native/src/lib.rs) ?

Although, I see no reason why we should do that, but I think people will request this in future. What do you think?

**Comment by wongjiahau** [comment]
@divy-work Yes I think we should.

**Comment by littledivy** [comment]
Closing due to #24
